sudo: true
dist: trusty
language: rust
addons:
  apt:
    packages:
      - git
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - wget
      - bzip2

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

rust:
  - nightly
  - beta
  - stable

os:
  - linux


before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
script:
  - |
    travis-cargo build &&
    travis-cargo test &&
    travis-cargo bench &&
    travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo --only stable coveralls --no-sudo --verify 
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget "https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/z3-4.4.1-x64-ubuntu-14.04.zip" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unzip z3-4.4.1-x64-ubuntu-14.04.zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PATH:./z3-4.4.1-x64-ubuntu-14.04/bin/ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget "http://fmv.jku.at/boolector/boolector-2.4.1-with-lingeling-bbc.tar.bz2" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bzip2 -d boolector-2.4.1-with-lingeling-bbc.tar.bz2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvf boolector-2.4.1-with-lingeling-bbc.tar ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -C boolector-2.4.1-with-lingeling-bbc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PATH:./boolector-2.4.1-with-lingeling-bbc/boolector/bin/ ; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "omNjOfgjm4B5HnmGRX4mFSFdzl8fRrGyzbsEoGhIrOtytctCFw8fWqyswXgc8fQWBT553HDaE+CkSTRExmvvqHwMwerWpOItR+ro+xdnSU4Fv2VzIfJfjY04KZh1nEQ2tZMqb3O19DDdwjl+QcIEWtQytD3BZS1ad0bRqvFh0UgR9BmhojSNaUIB9kHlz6T4DL9+wL6VuyLP3ZdusozA/SvdnyFLHdiVY736gEdtz9nyFMBKGTaQgssMQ2Km/jPi0MmVbCajPnWoGFkGmqTvzM1nsQ9edBdNKDT2ZYi2nBsE31f1DbGK8aSqdJtMq5Ggvz86QCVWEt+DnYQYuEEroZxu37roY+CJmDWd7psxsGobuYCk5emH2v5DrfJWPI4SAXP3hN623u2Z4WQ34SWSWT+2wR7vPg/0RYue2ilWM7oP8p6uUXVLrCphs6pnifeu8erkF9BxcIHCRIk+s3bBNbRdAwdDMFRwEZJ9tnSinyuntXEGCTTREYshcqpy3QrtOlMhgsSyJBhNXAQfRU8hE3EAS66/SwI3d3ybDZxutMaoZXEYhLb0qmh3+qAY1o3McpTnLbXZLRwHRPQbV8WMw1IxQn+g6tefOjZ8Idq9/diO+A4vG9Vwu1CHmR6XFyIIkgvqiijXcER+Ihu7iQYYYkE7hfiusHNOm6cqtA3snDk="
